import type {SupabaseClient} from "@supabase/supabase-js";
type Event="listing_submitted"|"listing_approved"|"listing_rejected";
type Listing={id:string;owner_id:string;title:string;city:string;locality:string;rejection_note?:string|null};
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,"0")).join("");
function template(event:Event,listing:Listing,name:string){const title=esc(listing.title),place=esc(`${listing.locality}, ${listing.city}`),reason=esc(listing.rejection_note||"Please review the feedback in your dashboard.");if(event==="listing_submitted")return{subject:`New property awaiting review: ${listing.title}`,text:`New property submitted: ${listing.title} in ${listing.locality}, ${listing.city}. Review it at https://reelestate.co.in/`,html:`<h2>New property awaiting review</h2><p><strong>${title}</strong></p><p>${place}</p><p>Poster: ${esc(name)}</p><p><a href="https://reelestate.co.in/">Open moderation desk</a></p>`};if(event==="listing_approved")return{subject:`Your property is live: ${listing.title}`,text:`Good news ${name}, your property "${listing.title}" was approved and is live: https://reelestate.co.in/property/${listing.id}`,html:`<h2>Your property is approved</h2><p>Good news ${esc(name)}, <strong>${title}</strong> is now live.</p><p><a href="https://reelestate.co.in/property/${listing.id}">View property</a></p>`};return{subject:`Action required for your property: ${listing.title}`,text:`Hello ${name}, your property "${listing.title}" was not approved. Reason: ${listing.rejection_note||"See your dashboard."} Update it at https://reelestate.co.in/`,html:`<h2>Your property needs changes</h2><p>Hello ${esc(name)}, <strong>${title}</strong> was not approved.</p><p><strong>Reason:</strong> ${reason}</p><p><a href="https://reelestate.co.in/">Open My posts</a></p>`}}
async function log(admin:SupabaseClient,listingId:string,event:Event,channel:string,recipient:string,status:string,providerId?:string,errorCode?:string){await admin.from("notification_deliveries").upsert({listing_id:listingId,event_type:event,channel,recipient_hash:await hash(recipient),status,provider_id:providerId||null,error_code:errorCode||null},{onConflict:"listing_id,event_type,channel,recipient_hash"})}
export async function notifyListing(admin:SupabaseClient,event:Event,listing:Listing){try{const {data:owner}=await admin.from("profiles").select("first_name,last_name,email,phone_e164").eq("id",listing.owner_id).single();const adminEmail=Deno.env.get("ADMIN_NOTIFICATION_EMAIL")||"kurrey007@gmail.com";const recipient=event==="listing_submitted"?{name:"ReelEstate admin",email:adminEmail,phone:Deno.env.get("ADMIN_NOTIFICATION_PHONE")||""}:{name:`${owner?.first_name||""} ${owner?.last_name||""}`.trim()||"Property owner",email:owner?.email||"",phone:owner?.phone_e164||""};const message=template(event,listing,recipient.name);
  if(recipient.email){const apiKey=Deno.env.get("RESEND_API_KEY"),from=Deno.env.get("NOTIFICATION_FROM_EMAIL");if(apiKey&&from){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({from,to:[recipient.email],subject:message.subject,html:message.html,text:message.text})});const body=await response.json().catch(()=>({}));await log(admin,listing.id,event,"email",recipient.email,response.ok?"sent":"failed",body.id,response.ok?undefined:`http_${response.status}`)}else await log(admin,listing.id,event,"email",recipient.email,"skipped",undefined,"provider_not_configured")}
  if(recipient.phone){const sid=Deno.env.get("TWILIO_ACCOUNT_SID"),token=Deno.env.get("TWILIO_AUTH_TOKEN"),from=Deno.env.get("TWILIO_FROM_PHONE");if(sid&&token&&from){const form=new URLSearchParams({To:recipient.phone,From:from,Body:message.text});const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:"POST",headers:{authorization:`Basic ${btoa(`${sid}:${token}`)}`,"content-type":"application/x-www-form-urlencoded"},body:form});const body=await response.json().catch(()=>({}));await log(admin,listing.id,event,"sms",recipient.phone,response.ok?"sent":"failed",body.sid,response.ok?undefined:String(body.code||`http_${response.status}`))}else await log(admin,listing.id,event,"sms",recipient.phone,"skipped",undefined,"provider_not_configured")}}
  catch(error){console.error("Notification dispatch failed",error instanceof Error?error.message:"unknown")}}
