import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";
import { Building2, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import type { Listing } from "../../../lib/types";
import EnquiryForm from "./EnquiryForm";

const client=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://placeholder.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"placeholder",{auth:{persistSession:false,autoRefreshToken:false}});
async function getListing(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))return null;const {data}=await client().rpc("get_public_listing",{p_listing_id:id});return data as Listing|null;}
const money=(minor:number,currency="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:0}).format(minor/100);

export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const listing=await getListing(id);if(!listing)return{title:"Property not found — ReelEstate"};const title=`${listing.title} — ReelEstate`;const description=`${listing.property_type} for ${listing.purpose} in ${listing.locality}, ${listing.city}. ${listing.description.slice(0,130)}`;return{title,description,alternates:{canonical:`/property/${listing.id}`},openGraph:{title,description,type:"website",url:`/property/${listing.id}`}};}

export default async function PropertyPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;const listing=await getListing(id);if(!listing)notFound();const storage=client().storage;const [{data:video},{data:poster}]=await Promise.all([storage.from("property-videos").createSignedUrl(listing.video_path,1800),listing.poster_path?storage.from("property-posters").createSignedUrl(listing.poster_path,1800):Promise.resolve({data:null})]);const contact=listing.contact_phone.replace(/\D/g,"");const facts=[listing.bedrooms!=null&&["Bedrooms",`${listing.bedrooms} BHK`],listing.bathrooms!=null&&["Bathrooms",listing.bathrooms],listing.carpet_area_sqft&&["Carpet area",`${listing.carpet_area_sqft.toLocaleString("en-IN")} sq.ft.`],listing.builtup_area_sqft&&["Built-up area",`${listing.builtup_area_sqft.toLocaleString("en-IN")} sq.ft.`],listing.furnishing_status&&["Furnishing",listing.furnishing_status.replaceAll("_"," ")],listing.facing&&["Facing",listing.facing.replaceAll("_"," ")],listing.floor_number!=null&&["Floor",listing.total_floors?`${listing.floor_number} of ${listing.total_floors}`:listing.floor_number],listing.parking_spaces!=null&&["Parking",listing.parking_spaces],listing.property_age_years!=null&&["Property age",`${listing.property_age_years} years`],listing.posted_by&&["Posted by",listing.posted_by]].filter(Boolean) as [string,string|number][];
  return <main className="property-page"><header className="property-page-header"><Link className="logo" href="/"><span><Building2/></span><b>Reel<span>Estate</span></b></Link><Link href="/">Browse properties</Link></header><section className="property-detail-layout"><div><div className="property-page-video">{video?.signedUrl?<video src={video.signedUrl} poster={poster?.signedUrl} controls playsInline preload="metadata"/>:<div className="video-loading">Video unavailable</div>}<span><ShieldCheck/> Reviewed video</span></div><div className="property-page-copy"><span className="property-pill">{listing.property_type} · For {listing.purpose}</span><h1>{listing.title}</h1><p className="detail-location"><MapPin/>{listing.locality}, {listing.city}</p>{listing.project_name&&<p className="project-name">{listing.project_name}</p>}<div className="detail-price">{money(listing.price_minor,listing.currency)}{listing.purpose==="rent"&&<small>/ month</small>}</div><div className="detail-facts">{facts.map(([label,value])=><span key={label}><small>{label}</small><b>{value}</b></span>)}</div>{listing.amenities&&listing.amenities.length>0&&<><h2>Amenities</h2><div className="amenity-pills">{listing.amenities.map(value=><span key={value}>{value}</span>)}</div></>}<h2>About this property</h2><p className="detail-description">{listing.description}</p><div className="detail-contact">{listing.contact_preference!=="whatsapp"&&<a href={`tel:${listing.contact_phone}`}><Phone/> Call</a>}{listing.contact_preference!=="call"&&<a href={`https://wa.me/${contact}`} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a>}</div></div></div><aside><EnquiryForm listingId={listing.id}/><div className="trust-detail"><ShieldCheck/><p><b>Reviewed before publication</b><br/>Confirm ownership, availability, and legal details independently before making any payment.</p></div></aside></section></main>;
}
